unbind = SUPER SHIFT, C
bindd = SUPER SHIFT, C, Claude, exec, omarchy-launch-webapp "https://claude.ai"

unbind = SUPER SHIFT, E
bindd = SUPER SHIFT, E, iCloud, exec, omarchy-launch-webapp "https://www.icloud.com/mail/"
