unbind = SUPER SHIFT, C
bindd = SUPER SHIFT, C, iCloud Calendar, exec, omarchy-launch-webapp "https://www.icloud.com/calendar/"

unbind = SUPER SHIFT, E
bindd = SUPER SHIFT, E, iCloud, exec, omarchy-launch-webapp "https://www.icloud.com/mail/"

unbind = SUPER SHIFT ALT, A
bindd = SUPER SHIFT ALT, A, Claude, exec, omarchy-launch-webapp "https://claude.ai"
bindd = SUPER SHIFT ALT, K, Grok, exec, omarchy-launch-webapp "https://grok.com"
